project:
  type: book

book:
  title: "Operaci√≥n Triunfo"
  author: "Sergio Delgado Quintero"
  chapters:
    - index.qmd
    - scrap.qmd
    - eda.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
