project:
  type: book

lang: es

book:
  title: "Operaci√≥n Triunfo"
  author:
    name: "Sergio Delgado Quintero"
    url: https://sdelquin.matraka.es
  chapters:
    - index.qmd
    - scrap.qmd
    - eda.qmd
  navbar:
    right:
      - icon: github
        href: https://github.com/sdelquin/ot
      - icon: globe
        href: https://sdelquin.matraka.es

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
